import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

<<<<<<< HEAD
import { CartProvider } from "./[slug]/menu/contexts/cart";

=======
>>>>>>> ef81cd64e8c0680f8065061362f31766bca48960
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FSW Donalds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
<<<<<<< HEAD
        <CartProvider>{children}</CartProvider>
=======
        {children}
>>>>>>> ef81cd64e8c0680f8065061362f31766bca48960
      </body>
    </html>
  );
}
